config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root "static#welcome"



  resources :sessions

  resources :users, only: [:new, :create] do
    resources :tasks, only: [:index, :show, :new]
  end

  resources :projects do
    resources :tasks, only: [:new, :show, :index, :create]
  end


  get '/signout', to: 'sessions#destroy'

  get '/tasks/:id/complete', to: "tasks#complete"

  get '/auth/facebook/callback' => 'sessions#create'

  get '/tasks/indexCompleted' => 'tasks#indexCompleted'

  get '/users/most_projects', to: "users#most_projects"

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true

  has_many :tasks
  has_many :users, through: :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :project, optional: true



  validates :name, presence: true
  validate :due_date_cannot_be_in_the_past

  scope :completed_tasks, -> {where(completed: true)}
  scope :over_due, -> {where("due_date > ?", Date.today)}
  scope :by_date_completed, ->  {order("date_completed DESC")}

  # custom validation
  def due_date_cannot_be_in_the_past
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "can't be in the past")
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :tasks
  has_many :projects, through: :tasks


  validates :email, :username, :password, presence: true
  validates :email, uniqueness: true

  # scope method to return which user has the most project
  scope :most_projects, -> {joins(:projects).group(:user_id).order("COUNT(*) DESC").first}



  def self.find_or_create_by_omniauth(auth_hash)

    self.where(email: auth_hash['info']['email']).first_or_create do |user|
      user.password = SecureRandom.hex
      user.username = auth_hash['info']['name']
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in
    !!session[:user_id]
  end

  helper_method :current_user, :logged_in
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login
  before_action :set_project, only: [:show, :edit, :update, :destroy]



  def index
    @projects = Project.all
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @projects}
    end
  end

  def show
    # @tasks = @project.tasks
    # render json: @tasks
    render json: @project
  end

  def new
    @project = Project.new
    render layout: false
  end

  def create

    @project = Project.new(project_params)
    if @project.save
      render json: @project
    end
    # if @project.save
    #   redirect_to projects_path
    # else
    #   render :new
    # end
  end

  def edit
    render layout: false
  end

  def update

    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require('project').permit(:name)
  end

  def require_login
    return head(:forbidden) unless session.include? :user_id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in
      redirect_to projects_path
      flash[:notice] = "You are already logged in."
    else
      @user = User.new
    end
  end

  def create
      if auth_hash
        #user signed in with omniauth
        @user = User.find_or_create_by_omniauth(auth_hash)

        session[:user_id] = @user.id
        #when user signs in they will see just their tasks and projects
        redirect_to projects_path

      else
      #regular sign in

        @user = User.find_by(email: params[:user][:email])

        #authenticate pw
        if @user && @user.authenticate(params[:user][:password])
          session[:user_id] = @user.id
          #when user signs in they will see just their tasks and projects
          redirect_to projects_path
        else
          #redirect to sign in page if authentificatin does not work

          redirect_to new_session_path
        end
      end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  private

  def auth_hash

    request.env['omniauth.auth']
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
layout 'sessions'

def welcome
  if logged_in
    redirect_to projects_path
    flash[:notice] = "You are already logged in."
  end

end
end

app/controllers/tasks_controller.rb
require 'date'

class TasksController < ApplicationController
  before_action :require_login
  before_action :set_task, only: [:edit, :update, :destroy, :complete]



  def index
    if params[:user_id]
      if User.find(params[:user_id]) == current_user
        @user = User.find(params[:user_id])
        @tasks = @user.tasks
      else
        redirect_to projects_path
        flash[:notice] = "Unauthorized Access."
      end
    else
      @tasks = Task.all
    end
  end

  def indexCompleted
    # use scope method to get only completed tasks
    @tasks = Task.completed_tasks
    render json: @tasks
  end

  def new
    if params[:user_id]
      @user = User.find(params[:user_id])
      @task = Task.new(user_id: @user.id)

    else
      @user = nil
      @task = Task.new
    end


  end

  # def create
  #   @task = Task.new(task_params)
  #
  #   if @task.save
  #      redirect_to projects_path
  #   else
  #     render :new
  #   end
  # end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build(task_params)
    @task.save
    # return JSON to append new task to dom
    render json: @task
  end

  def edit
    render layout: false
  end

  def show
    task = Task.find(params[:id])
    # render JSON to append to DOM
    render json: task
  end

  def update
    if @task.update(task_params)
      render json: @task, status: 201
    else
      render :edit, layout: false, status: 400
    end

  end

  def complete
    @task.update(completed: true, date_completed: DateTime.now)
    render json: @task
  end

  def destroy
    @task.destroy
    redirect_to projects_path
  end


  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name,:due_date, :description, :user_id, :project_id)
  end

  def require_login
    return head(:forbidden) unless session.include? :user_id
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def most_projects
    @user = User.most_projects
  end


  def new
    if logged_in
      redirect_to projects_path
      flash[:notice] = "You are already logged in."
    else
      @user = User.new
      render layout: 'sessions'
    end
  end

  def create

    @user = User.new(user_params)

    if @user.save

      session[:user_id] = @user.id
      redirect_to projects_path
    else
      render :new, layout: 'sessions'
    end

  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end


  # def show
  #   @user = User.find_by(params[:id])
  #
  #   @tasks = @user.tasks
  # end

  private


  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>ProjectManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap core CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">




    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>


  </head>

  <body class="">

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand">Project Manager</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">


          <li class="nav-item">
            <a class="btn btn-primary" href="/signout">Log Out</a>
          </li>

          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown link
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> -->
        </ul>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Project Manager</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/sessions/new">Sign In</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_path  %>">Sign Up</a>
          </li>

        </ul>
      </div>
    </nav>

   <%= yield %>

  </body>
</html>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@project.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @project do |f| %>
<div class="form-row">
    <div class="col-7">
      <%= f.text_field :name, placeholder: "Project Name", class: "form-control" %>
    </div>



    <div class="col-2 mb-2">
      <%= f.submit "Create", class: "btn btn-primary" %>
    </div>
  </div>
<% end  %>

app/views/projects/edit.html.erb
  <%= render 'projects/form',  :locals => {:@project => @project} %>

app/views/projects/index.html.erb
<br>






<div class="container-fluid mx-5 ">
  <div class="row" id="projects">

    <div class="col-sm-9">
      <div class="row" id="project-tiles">




      <div class="col-sm-3 mb-3 ">
        <div class="col-md-12 bg-secondary pb-3 rounded">
          <br>
          <button id="add-project" type="button" class="text-center col-md-12 py-3 rounded btn btn-outline-light" data-toggle="collapse" data-target="#newProjectForm" aria-expanded="false" aria-controls="">New Project</button>
          <div id="newProjectForm">
          </div>
        </div>
      </div>

        <% @projects.all.each do |project| %>
              <div class="col-sm-3 mb-3 ">
                <div id="project-<%= project.id %>" class="col-md-12 bg-secondary pb-3 rounded">

                  <br><div class="btn-group">
                    <button type="button" data-project-id="<%= project.id %>" class="project-more btn btn-secondary text-center py-3 rounded btn" data-toggle="collapse" data-target="#project-<%= project.id %>-tasks"><%= project.name %> </button>

                    <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" id="dropdownMenuReference" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-reference="parent">
                      <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
                      <!-- <a class="dropdown-item" href="#">Edit Project</a> -->
                      <a class="projectDelete dropdown-item" data-project-id="<%= project.id %>" href="#">Delete Project</a>
                    </div>
                  </div>

                  <div id="project-<%= project.id %>-tasks" class="tasks">
                  </div>

                  <div id="newTaskForm-<%= project.id %>" class="collapse">
                  </div>

                <br><button type="button" class="new-task btn btn-outline-light m-1" data-project-id="<%= project.id %>" data-toggle="collapse" data-target="#newTaskForm-<%= project.id %>" aria-expanded="false" aria-controls="" >+ Add Task</button>


                </div>
              </div>
            <% end  %>
          </div>
        </div>
    <div id="completed" class="col-sm-3">
      <button type="button" id="order-tasks">Order Tasks</button>
      <div id='completed-tasks' class="col-md-12 py-3 rounded" style='background-color: #C0C0C0'>

      </div>
    </div>


  </div>  <!-- ROW -->




</div> <!-- CONTAINER  -->






<!--  MODAL -->
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content" >
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" >

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
  <%= render 'projects/form',  :locals => {:@project => @project} %>

app/views/projects/show.html.erb
<h1>
<%= @project.name %>
</h1>

<%= link_to "Edit Project", edit_project_path(@project) %>
<%=   link_to 'Delete Project', @project, method: :delete, data: { confirm: 'Are you sure?' } %> 
<% tasks = @project.tasks %>
<%= render partial: 'tasks/tasklist', :locals => {:@tasks => tasks}%>

app/views/tasks/_completed.html.erb
<table style="width:100%">
  <tr>
    <th>Task</th>
    <th>Due Date </th>
    <th>Assigned To</th>
    <th>Delete</th>
    <th>Complete<th>
  </tr>

  <% @tasks.all.each do |task| %>
  <% if task.completed %>
    <tr>
      <td><%= task.description %></td>
      <td> <%= task.due_date.strftime("%B %d, %Y") unless task.due_date.nil?  %> </td>
      <td> <%= task.user.username  %> </td>
      <td> <%=  link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }  %> </td>
      <td> Completed </td>
    </tr>
  <% end %>

  <% end  %>

</table>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@task.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<br>


  <%= form_for(@task) do |f| %>

  <div class="form-group">
    <%= f.label :name, "name" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_field :description, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :due_date, "Due date"%>
    <%= f.date_select :due_date, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :project_id, "Select the Project for this task:" %><br>
    <%= f.collection_select :project_id, Project.all, :id, :name %>
  </div>



    <% if @user %>
       <%= f.hidden_field :user_id  %>
    <% else  %>
      <div class="form-group">
        <%= f.label :user_id, "Select the User for this task:" %><br>
        <%= f.collection_select :user_id, User.all, :id, :username %>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end  %>

app/views/tasks/_tasklist.html.erb
<h2>  <%= link_to "#{project.name}", project_path(project)%></h2>

  <table class = "table table-striped" >
    <thead class = "thead-dark">
      <tr>
        <th scope="col">Task</th>
        <th scope="col">Project</th>
        <th scope="col">Due Date </th>
        <th scope="col">Assigned To</th>
        <th scope="col">Edit/Delete</th>
        <th scope="col">Complete<th>
      </tr>
    </thead>
    <tbody>


    <% @tasks.all.each do |task| %>
      <% if !task.completed %>
        <tr scope="row">
          <td><%= task.description %></td>
          <td> <%= task.project.name %> </td>
          <td> <%= task.due_date.strftime("%B %d, %Y") unless task.due_date.nil?  %> </td>
          <td> <%= task.user.username  %> </td>
          <td> <%= link_to "Edit", edit_task_path(task) %> / <%=  link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }  %> </td>
          <td> <a class="btn btn-outline-success" href="/tasks/<%= task.id %>/complete">Complete </a>  </td>
        </tr>
      <% end %>
    <% end  %>
    </tbody>

  </table>

app/views/tasks/edit.html.erb
  <%= render 'form',  :locals => {:@task => @task} %>

app/views/tasks/index.html.erb
<!-- shows just the user's tasks  -->
<% if @user %>
<div class="container">
  <h1>Welcome, <%= @user.username if @user%>  </h1><br>
  <h2>Here are your tasks:</h2><br>
  <%= link_to "Give yourself a new task!", new_user_task_path(@user) %>
  <br><br>
</div>
<% end  %>

<div class="container">
  <%= render 'tasklist', :locals => {:@tasks => @tasks} %>
</div>


<br><br>

<div class="container">

  <h2>Completed Tasks</h2>

  <%= render 'completed', :locals => {:@tasks => @tasks} %>
</div>

app/views/tasks/new.html.erb
  <%= render 'tasks/form',  :locals => {:@task => @task} %>

app/views/users/most_projects.html.erb
<%= @user.username %> has the most projects!

app/views/users/new.html.erb
<br>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<br>

<div class="container">


<%= form_for @user , :html => {class: "form-signin"} do |f| %>

  <div class="form-group">
    <%= f.label :email, "E-mail" %>
    <%= f.text_field :email, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :username, "Username" %>
    <%= f.text_field :username, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :password, "Password"%>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field  :password_confirmation , class: "form-control"%>
  </div>

  <div class="actions">
    <%= f.submit "Sign Up", class: "btn btn-primary" %>
  </div>

  <% end %>


</div>

app/views/users/show.html.erb
<!-- shows just the user's tasks  -->

<h1>Welcome, <%= @user.username %>  </h1>

<h2>Here are your tasks:</h2>


<!-- Order tasks by due date -->
<!-- filter by project -->
<ul>
  <% @tasks.all.each do |task| %>

    <li><%= task.description %></li>
  <% end  %>
</ul>

  <!-- link to create new task  -->
  

  <!--  link to view all projects and tasks -->
  <%= link_to "See all Projects/Tasks", projects_path %>